# === Server Config ===
server:
  port: 8080

# === H2 Database Config ===
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ""

  # === JPA / Hibernate ===
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # === H2 Console ===
  h2:
    console:
      enabled: true
      path: /h2-console
